#ifndef WRAPPERS_COMMAND_WRAPPER_HPP
#define WRAPPERS_COMMAND_WRAPPER_HPP
#include <vector>

namespace wrappers
{
    struct CommandWrapper
    {
        //stores binary blob generated by boost serialization
        std::vector<unsigned char> binaryData;
    };
}




#endif